#ifndef COMMON_H
#define COMMON_H

#include "ndds/ndds_cpp.h"
#include "ndds/ndds_namespace_cpp.h"

// files generated by rtiddsgen
#include "generated/type1.h"
#include "generated/type1Support.h"
#include "generated/type2.h"
#include "generated/type2Support.h"
#include "generated/type3.h"
#include "generated/type3Support.h"
#include "generated/type4.h"
#include "generated/type4Support.h"

const char *topic1_name = "Topic 1";
const char *topic2_name = "Topic 2";
const char *topic3_name = "Topic 3";
const char *topic4_name = "Topic 4";

#endif
